### PR TITLE
added geologic_time to search documents

### PR DESCRIPTION
**Pull request by zednis**
Updates:
- [x] updated ingest script to make use of geologic-time resolver service to get geologic intervals the min - max age intersect
- [x] added geologic interval facets to browser and map

screen shot 2016-03-25 at 3 19 21 pm

### CODE REVIEW

**Comment by zednis** [comment]
@zhonghao1014 please review this pull request when you have time.  Thanks.

**Comment by zednis** [comment]
@xgmachina @kolans what do you think of the proposed facets? (see screenshot)

**Comment by zhongh** [comment]
@zednis I think we can merge this into master as there is no conflict and it looks amazing.

One little concern is, after merging this into master, I will need to merge these changes in master into my current branch "json-structure-revisions", since in the branch "json-structure-revisions" branch, "mineral" objects are renamed as "mineral-species" along with some other structural changes. But I don't think it will be too much an issue, since if there are conflicts, github and retain the differences and let me deal with the conflicts. Right?

**Comment by zednis** [comment]
@zhonghao1014 I think we should be able to merge the updated master into your branch with no difficulty.

**Comment by zhongh** [comment]
@zednis Sure that's what I thought but not sure about. So with the confirmation let's merge this? I think everything looks good on this branch. :shipit:

**Comment by zednis** [comment]
Great.  I'll merge & close the pull request and work to make sure your branch picks up the changes.

**Pull request merged**
