### PR TITLE
Age facets in browser

### PR DESCRIPTION
**Pull request by zhongh**
I made changes to the html file, and only necessary changes to the ingest code and mapping file since we need the age to be numerical instead of strings.

### CODE REVIEW

**Comment by zhongh** [comment]
**ISSUE**:
I generated a new bulk file (with numerical age values) and upload the mapping (with ages typed as "double") and the bulk file. However, the "max-age" facet works but the "min-age" facet does not. To further explain:
- If I comment out the "min-age" facet, the "max-age" alone works, with no error messages.
- If I have "min-age" alone, or both facets on, the browser does not show anything and gives error message in console: 

GET http://localhost:9200/dtdi/mineral-observation/_search?callback=jQuery1710597245390759781_1457796479276&source=%7B%22query%22%3A%7B%22match_all%22%3A%7B%7D%7D%2C%22from%22%3A0%2C%22size%22%3A20%2C%22facets%22%3A%7B%22mineral.mineral-name-plain.exact%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22mineral.mineral-name-plain.exact%22%2C%22size%22%3A115%2C%22order%22%3A%22count%22%7D%7D%2C%22mineral.chemistry-elements-list.exact%22%3A%7B%22terms%22%3A%7B%22field%22%3A%22mineral.chemistry-elements-list.exact%22%2C%22size%22%3A115%2C%22order%22%3A%22count%22%7D%7D%2C%22locality.min-age%22%3A%7B%22range%22%3A%7B%22locality.min-age%22%3A%5B%7B%22to%22%3A100%7D%2C%7B%22to%22%3A200%2C%22from%22%3A100%7D%2C%7B%22from%22%3A200%7D%5D%7D%7D%2C%22..............

**Comment by zednis** [comment]
The commits you have made so far look good.

I wonder if this error is in the bulk file? The error appears to be in the min-age values.  Check the min-age values in the bulk file generated by the script to see if there are any questionable values - something that might not be properly processed by ES.

**Comment by zhongh** [comment]
There are no questionable values in the bulk file. All "min-age" values are double numbers, the same as "max-age" values. I also tried creating a bulk file with only 1 entry in it, and uploaded it. Still, only the "max-age" facet works; and as long as the "min-age" facet is uncommented, the browser breaks down.

I changed the naming "min-age" to something else, "minimum-age", "minage", etc, then it all works. Then I changed it back to "min-age", it works again. I am not sure what happened but now it works.

**Comment by zhonghao1014** [comment]
@zednis I changed the naming "min-age" to something else, "minimum-age", "minage", etc, then it all WORKS! What do you think the problem is?

**Comment by zhongh** [comment]
Ready to merge this little branch on age facets? @zednis 
screen shot 2016-03-15 at 1 16 59 pm

**Comment by zednis** [comment]
Looks good!  What was the issue?  The fixing commit makes it look like a hidden character in the mapping JSON.

Let's get feedback from @xgmachina and @kolans about the facet ranges (perhaps we add more values above 200) and then merge.

**Comment by zednis** [comment]
Perhaps the facet ranges are every 100 Ma until "greater than 1000 Ma"?

**Comment by zednis** [comment]
@xgmachina  ... and does it make sense for min and max age facets to have the same range granularity?  Perhaps min age should be more specific?

**Comment by xgmachina** [comment]
I do not have much comments on this issue. This is about the age of mineral species and I suggest we ask Josh for some suggestions. I can email him.

**Comment by zhongh** [comment]
Maybe we can merge this pull request for now as its goal has been fulfilled, and can have further discussion on details on age granularity later on? In that way I can move on to fix other issues on the plate.

**Comment by zhongh** [comment]
Fixes #19

**Comment by zednis** [comment]
Let's see if Josh responds today and if so incorporate his changes.  If not, we can merge at the end of the day and incorporate his feedback later in a different pull request.

**Comment by zhongh** [comment]
:+1: I also marked above that this pull request will fix issue #19. Did I do it the right way?

**Comment by zednis** [comment]
@zhonghao1014 I think so.  When this pull request is merged it should close issue #19.

**Comment by zhongh** [comment]
:+1:

**Comment by kolans** [comment]
@zhonghao1014 @zednis We talked about color coding the locations with age so it might be useful for the min/max ranges to be the "Age" ranges. Typically a geologist will look for minerals in an "Age" range rather than a granular range. Let's see what Josh thinks too though.

**Comment by zhongh** [comment]
@kolans What are the several age ranges that a geologist looks at? Maybe we can use those age ranges for both min and max age instead of the initial ranges we have for now. Just a thought and, right, let's wait for Josh.

**Comment by kolans** [comment]
The age ranges are the min/max for an "Age", "Epoch", "Period", etc. on the Geologic Time Scale, ie, Early Jurassic (201-174Ma), Late Devonian (383-359Ma), Messinian (7.2-5.3Ma), etc.

**Comment by zednis** [comment]
My intention is to add additional facets later based on age, epoch, period, etc.  The geologic time resolver service was developed so that would could pass a min/max value to it during ingest and get back the intersecting geologic intervals, this information would then be part of the search document JSON and could be used with facets.

Perhaps age, epoch, and period facets would replace the min/max facets?

**Pull request merged**
