### PR TITLE
Relocate ingest resources

### PR DESCRIPTION
**Pull request by zhongh**
@zednis :
- The ingest script is relocated under ingest/
- Sample .csv files are relocated under ingest/ too. We are still waiting for RRUFF people (Josh, etc) to provide us automatic access to the data, and for now we still need to obtain the .csv files one-by-one. Once we have direct access to the data, we can make according changes to the ingest scripts and remove the sample data file.
- Other temporary files are not longer necessary and are deleted along with example/

### CODE REVIEW

**Comment by zhongh** [comment]
Fixed #42

**Comment by zednis** [comment]
Let's add a /ingest/resources directory and put the CSVs in it.

**Comment by zhonghao1014** [comment]
Ready to ship? @zednis

**Comment by zhongh** [comment]
ready to ship this too? @zednis

**Comment by zednis** [comment]
:shipit:

**Pull request merged**
